---
title: title
author: author
institute: institute
format: html
---

# Lib
```{r}
#| output: false

library(data.table)
library(R.utils)
```

# Data
```{{r}}
# Multi-ancestry meta-analysis summary stats
ta <- fread("../data/DIAMANTE2022/sumstat/DIAMANTE-TA.sumstat.txt.gz", header=T)

# Ancestry-specific
eas <- fread("../data/DIAMANTE2022/sumstat/DIAMANTE-EAS.sumstat.txt.gz", header=T)
eur <- fread("../data/DIAMANTE2022/sumstat/DIAMANTE-EUR.sumstat.txt.gz", header=T)
sas <- fread("../data/DIAMANTE2022/sumstat/DIAMANTE-SAS.sumstat.txt.gz", header=T)
```
```{r}
gckr <- fread("../data/DIAMANTE2022/fine_mapping/finemap.GCKR.rs1260326.txt.gz", header=T)
```

# Bayes factor
Ancestry specific: for each SNV, $\text{BF} = \exp(\frac{D-\ln K}{2} )$ \
Where deviance $D = b^2/SE^2$
Where beta $b = log(OR)$ \
See [Majahan 2022](https://doi.org/10.1038/s41588-022-01058-3)'s [supplementary note](https://www.nature.com/articles/s41588-022-01058-3#Sec34), pg 13.
No finer-grain ancestry-level summary stats available, only ancestry-level. Therefore, assumed every SNV is present in all 122 GWAS.
```{{r}}
b <- ta$`Fixed-effects_beta`
se <- ta$`Fixed-effects_SE`
d <- b^2/se^2

bf <- exp(( d-(4*log(122)) )/2)
```
```{r}

```




<!--
fm1 <- fread("../data/DIAMANTE2022/fine_mapping/finemap.ABCB10-NUP133.rs348330.txt.gz", header=T)
fm_gckr <- fread("../data/DIAMANTE2022/fine_mapping/finemap.GCKR.rs1260326.txt.gz", header=T)
# rs348330, chr1:229672955 is at index 732868: which(ta$rsID == rs348330)
ta[732868,]
log(bf[732868])
#fm2 <- fread("../data/DIAMANTE2022/fine_mapping/finemap.ABO.rs505922.txt.gz", header=T)


ta[chrposID == "chr1:229578794"]
ta[chrposID == "chr9:136149229"]


#my_fm$P <- `MR-MEGA_p-value_association`
-->
